In [124]:
import struct
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [125]:
import os
# lead training data
def load_mnist():
    """Load MNIST data"""
    labels_path = os.path.join('train-labels-idx1-ubyte')
    images_path = os.path.join('train-images-idx3-ubyte')
    
    with open(labels_path, 'rb') as lbpath:
        magic, n = struct.unpack('>II',lbpath.read(8))
        labels = np.fromfile(lbpath,dtype=np.uint8)
        
    with open(images_path, 'rb') as imgpath:
        magic, num, rows, cols = struct.unpack('>IIII',imgpath.read(16))
        images = np.fromfile(imgpath,dtype=np.uint8).reshape(len(labels), 784)# each row represents a image

    return images, labels

X_train, y_train = load_mnist()
X_train = X_train.astype(float)
y_train = y_train.astype(float)

In [126]:
X_train.shape

(60000, 784)

In [127]:
X_train[0,1:200]

array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   

In [128]:
y_train.shape

(60000,)

In [129]:
y_train[0:10]

array([5., 0., 4., 1., 9., 2., 1., 3., 1., 4.])

In [130]:
# load testing data
def load_mnist():
    """Load MNIST data"""
    labels_path = os.path.join('t10k-labels-idx1-ubyte')
    images_path = os.path.join('t10k-images-idx3-ubyte')
    
    with open(labels_path, 'rb') as lbpath:
        magic, n = struct.unpack('>II',lbpath.read(8))
        labels = np.fromfile(lbpath,dtype=np.uint8)
        
    with open(images_path, 'rb') as imgpath:
        magic, num, rows, cols = struct.unpack('>IIII',imgpath.read(16))
        images = np.fromfile(imgpath,dtype=np.uint8).reshape(len(labels), 784)# each row represents a image

    return images, labels

X_test, y_test = load_mnist()
X_train = X_train.astype(float)
y_train = y_train.astype(float)
X_test.shape

(10000, 784)

In [131]:
# export image with label 0 and label 9
X_train = X_train[(y_train == 0) | (y_train == 9)]
y_train = y_train[(y_train == 0) | (y_train == 9)]
y = y_train.astype(float)
y_train.shape

(11872,)

In [132]:
y_train[0:10]

array([0., 9., 9., 0., 9., 9., 0., 0., 9., 9.])

In [133]:
X_test = X_test[(y_test == 0) | (y_test == 9)]
y_test = y_test[(y_test == 0) | (y_test == 9)]
y_test = y_test.astype(float)

In [134]:
y_test[0:10]

array([0., 9., 9., 0., 9., 0., 9., 9., 0., 0.])

In [135]:
for i,k in enumerate(y_train):
    if k == 9:
        y_train[i]= 1
    else:
        y_train[i]= -1

In [136]:
y_train[0:10]

array([-1.,  1.,  1., -1.,  1.,  1., -1., -1.,  1.,  1.])

In [137]:
for i,k in enumerate(y_test):
    if k == 9:
        y_test[i]= 1
    else:
        y_test[i]= -1

In [138]:
y_test[0:10]

array([-1.,  1.,  1., -1.,  1., -1.,  1.,  1., -1., -1.])

In [139]:
import math

In [140]:
## generate gaussian matrix
def gen_gaussion(m):
    k = m*n
    s = np.random.normal(0, 1, k).reshape(m, n)
    Gaussion = np.mat(s)
    return Gaussion

n = len(X_train[1,])
m = int(n * math.log(n))
Gau = gen_gaussion(m)

In [141]:
# mapping X into a higher dimension
def mapping(X):
    X_matrix = np.transpose([np.mat(X)])
    X_map = np.transpose(1/math.sqrt(m) * np.sign(Gau * X_matrix))
    return X_map 

X_maptrain = mapping(X_train)
X_maptest = mapping(X_test)

In [142]:
X_maptrain.shape

(11872, 5224)

In [170]:
H

array([[ 1.        , -0.26416539, -0.20788668, ...,  0.48621746,
        -0.27565084, -0.25880551],
       [-0.26416539,  1.        ,  0.39624809, ..., -0.14548239,
         0.3085758 ,  0.30015314],
       [-0.20788668,  0.39624809,  1.        , ..., -0.20635528,
         0.39548239,  0.37557427],
       ...,
       [ 0.48621746, -0.14548239, -0.20635528, ...,  1.        ,
        -0.22511485, -0.19831547],
       [-0.27565084,  0.3085758 ,  0.39548239, ..., -0.22511485,
         1.        ,  0.66845329],
       [-0.25880551,  0.30015314,  0.37557427, ..., -0.19831547,
         0.66845329,  1.        ]])

In [166]:
# Generate matrix H for cvxopt
X = X_maptrain
y = y_train.reshape(-1, 1) * 1.
i,j = X.shape
X_dash = np.zeros(shape=(i,j))
for t,item_y in enumerate(y):
        X_dash[t,] = item_y * X[t,]
        
H = np.dot(X_dash , X_dash.T) * 1.

In [171]:
from cvxopt import matrix as cvxopt_matrix
from cvxopt import solvers as cvxopt_solvers


# Converting into cvxopt format
P = cvxopt_matrix(H)
q = cvxopt_matrix(-np.ones((i, 1)))
G = cvxopt_matrix(-np.eye(i))
h = cvxopt_matrix(np.zeros(i))
A = cvxopt_matrix(y.reshape(1, -1))
b = cvxopt_matrix(np.zeros(1))

# Setting solver parameters (change default to decrease tolerance) 
cvxopt_solvers.options['show_progress'] = False
cvxopt_solvers.options['abstol'] = 1e-10
cvxopt_solvers.options['reltol'] = 1e-10
cvxopt_solvers.options['feastol'] = 1e-10

In [172]:
# Run solver
sol = cvxopt_solvers.qp(P, q, G, h, A, b)
alphas = np.array(sol['x'])

In [174]:
# w parameter in vectorized form
w = ((y * alphas).T @ X).reshape(-1,1)

# Selecting the set of indices S corresponding to non zero parameters
S = (alphas > 1e-4).flatten()

# Computing b
b = y[S] - np.dot(X[S], w)

# Display results
print('Alphas = ',alphas[alphas > 1e-4])
print('w = ', w.flatten())
print('b = ', b[0])

Alphas =  [7.61351677e+00 1.02275481e+00 1.46805091e+00 3.40658341e+00
 6.41974494e+00 7.20572596e-01 4.91903679e-01 5.01280118e+00
 1.22930437e+00 1.64492402e+00 4.53408698e+00 3.72702720e-01
 7.32692904e-01 5.84518510e-01 1.33733895e+00 9.50338360e-01
 4.51985432e-01 6.91491463e-01 7.38621491e-01 2.68594053e-01
 7.09794959e-01 1.05307804e+00 2.69197861e+00 2.54563568e+00
 5.29147242e-01 6.63706901e-03 2.96748061e-02 1.14095968e-01
 2.14618328e+00 1.13773021e+00 1.11605932e+00 3.34810404e-01
 1.18917920e-01 3.65265895e+00 4.83413227e-01 1.92446207e-01
 8.82502015e-01 5.27066700e-01 2.74544945e+00 9.16673618e-01
 2.64460631e+00 7.69329570e-01 2.03548186e-01 1.16979348e-01
 6.13070542e-01 1.03603272e-01 7.27577312e-03 1.19608241e-01
 1.33169600e+00 8.96934740e-01 9.16921994e-01 1.21201314e-01
 7.48723688e-01 4.31707709e-01 7.70204386e-01 3.80980886e+00
 1.36030005e-01 3.69190232e-02 6.21886655e-02 4.30103324e+00
 3.44390324e-01 3.12373906e+00 3.28066667e-01 4.78519944e-01
 1.06695785e+0

In [175]:
print(w.shape)

(5224, 1)


In [187]:
# test our svm algorithm
error = 0
y_test = y_test.reshape(-1, 1) * 1.
for i,k in enumerate(X_maptest):
    y_pred = np.dot(w.T, np.array(k.T))+b[0]
    if y_pred * y_test[i] < 0:
        error += 1
error

9

In [189]:
accuracy_rate = 1 - error / len(y_test)
accuracy_rate

0.995475113122172

In [190]:
len(y_test)

1989

In [ ]:
# reference for cvxopt: https://xavierbourretsicotte.github.io/SVM_implementation.html
# SVM 中文解释： https://wizardforcel.gitbooks.io/dm-algo-top10/content/svm-3.html